{
 "title": "YARA Email Scanner Dashboard",
 "tags": [
  "email",
  "security",
  "scanner",
  "yara"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Clean Email Percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(100 * (count_over_time({job=\"scanner\"} |= \"successfully\" [6h]) / (count_over_time({job=\"scanner\"} |= \"successfully\" [6h]) + count_over_time({job=\"scanner\"} |= \"WARNING\" [6h]) + 1)))"
    }
   ]
  },
  {
   "title": "Quarantined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"scanner\"} |= \"WARNING\" [6h]))"
    }
   ]
  },
  {
   "title": "Top 5 YARA Rules Triggered",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (yara_hit) (count_over_time({job=\"scanner\"} |= \"WARNING\" | json | line_format \"{{.yara_hit}}\" [6h])))"
    }
   ]
  },
  {
   "title": "Clean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"scanner\"} |= \"successfully\" [6h]))"
    }
   ]
  },
  {
   "title": "Threat Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by() (count_over_time({job=\"scanner\"} |= \"WARNING\" [1m]))",
     "legendFormat": "Quarantined threats"
    }
   ]
  },
  {
   "title": "Quarantined Emails",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"scanner\"} |= \"WARNING\""
    }
   ]
  },
  {
   "title": "Recent Scanner Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{job=\"scanner\"}"
    }
   ]
  }
 ]
}